###This is the CFN to create the CICD Pipeline which will in turn deploy the actual infrastruture.
#If this file is changed, the CICD Stack in AWS will be changed through change-sets. Otherwise the update will make no change
#The change is triggered by Github itself through workflows

#Author: Pratyay Pal [https://github.com/Pratyay-Pal]

#Change values in Parameter section only. Leave the rest as it is.
Parameters:
  #Overridden in github-actions.yml by S3_Bucket_Name. If you need to change it, change it there
  #Artifact store for Codepipeline. Codepipeline will generate artifacts for the subsequent stages which are stored here.
  ArtifactStoreBucket:
    Type: String
    Default: aws-infra-as-code-cfn-store
    Description: Artifact store for Codepipeline. 
  
  #Overridden in github-actions.yml by S3_Bucket_Name. If you need to change it, change it there
  #Bucket where Source Artifact for Codepipeline is stored. This is where the CFN for your stack will go to. Github actions will auomatically place the ZIP here.
  SourceArtifactBucket:
    Type: String
    Default: aws-infra-as-code-cfn-store
    Description: Bucket where Source Artifact for Codepipeline is stored.
  
  #Overridden in github-actions.yml by Infrastructure_Stack_Zip_File. If you need to change it, change it there
  #Source Artifact for Codepipeline. Github actions will auomatically ZIP the Infrastructure CFN.
  SourceArtifact:
    Type: String
    Default: infrastructure-cfn.zip
    Description: Source Artifact for Codepipeline. Must be ZIP.

  #Overridden in github-actions.yml by Infrastructure_Stack_Yaml_File. If you need to change it, change it there
  #Source Artifact Code for Codepipeline. Github actions will auomatically ZIP the Infrastructure CFN.
  SourceArtifactCode:
    Type: String
    Default: infrastructure-cfn.yaml
    Description: Infrastruture as code. Must be YAML/JSON.

  #Necessary Roles
  CFNRoleARN:
    Type: String
    Default: AWS-CFN-Infra-Role
    Description: Role that Cloudformation assumes when creating resources on AWS.
  
  #Necessary Roles
  Lambda2S3RoleARN:
    Type: String
    Default: AWS-Lambda-S3-Role
    Description: Role that Cloudformation assumes when creating resources on AWS.

  #Name of Lambda which will delete files from S3
  Lambda2DeleteS3FilesName:
    Type: String
    Default: lambda-to-delete-S3-files
    Description: Name of Lambda which deletes files in S3 before bucket deletion.
  
  #Overridden in github-actions.yml by Infrastructure_Stack_Name. If you need to change it, change it there
  #Name of the stack in which your CFN will be deployed to
  InfrastructureDeploymentStackName:
    Type: String
    Default: infrastructure-stack
    Description: Name of stack of the Infrastructure.

Resources:
  S3BucketToStoreCFN:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SourceArtifactBucket
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: Delete

  LambdaRole2Connect2S3:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref Lambda2S3RoleARN
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: Lambda2S3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketToStoreCFN}
                  - !Sub arn:aws:s3:::${S3BucketToStoreCFN}/*
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

  CFNRole2CreateResources:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref CFNRoleARN
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: Admin
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "*"
                Resource:
                  - "*"

  Lambda2EmptyBucketBeforeDestroying:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Ref Lambda2DeleteS3FilesName
      Runtime: "python3.12"
      Timeout: 60
      Role: !GetAtt LambdaRole2Connect2S3.Arn
      Handler: "index.lambda_handler"
      Code: 
        ZipFile: |
          #!/usr/bin/env python
          import json
          import boto3
          import cfnresponse

          s3 = boto3.client('s3')
          response_data = {}
          def lambda_handler(event, context):
              print("Event : "+str(event))
              bucket_name=event['ResourceProperties']['bucket_name']
              try:
                  if event['RequestType'] == 'Delete':                
                      allObjs = s3.list_object_versions(Bucket=bucket_name)
                      for objVer in allObjs.get('Versions', []):
                          s3.delete_object(
                              Bucket=bucket_name,
                              Key=objVer['Key'],
                              VersionId=objVer['VersionId']
                          )                  
                      for objDelMrkr in allObjs.get('DeleteMarkers', []):
                          s3.delete_object(
                              Bucket=bucket_name,
                              Key=objDelMrkr['Key'],
                              VersionId=objDelMrkr['VersionId']
                          )
                  print("Execution succesfull!")
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)
              except Exception as e:
                  print("Execution failed...")
                  print(str(e))
                  response_data['Data'] = str(e)
                  cfnresponse.send(event, context, cfnresponse.FAILED, response_data)
  
  LambdaCustomResource:
    Type: Custom::LambdaCustomResource
    Properties:
      ServiceToken: !GetAtt Lambda2EmptyBucketBeforeDestroying.Arn
      bucket_name: !Ref S3BucketToStoreCFN ###THIS IS NEEDED TO CREATE DEPENDENCY BETWEEN DELETION LAMBDA(Lambda2EmptyBucketBeforeDestroying) AND S3 BUCKET
      ### IF THIS IS NOT PRESENT CFN WILL TRY TO DESTROY THE S3 BEFORE IT IS EMPTIED

  InfrastructureDeployment:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref S3BucketToStoreCFN
        Type: S3
      Name: infrastructure-deployment
      PipelineType: V2
      RoleArn: !GetAtt CFNRole2CreateResources.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                PollForSourceChanges: false
                S3Bucket: !Ref S3BucketToStoreCFN
                S3ObjectKey: !Ref SourceArtifact
              OutputArtifacts: 
                - Name: SourceArtifact
        - Name: Deploy
          Actions:
            - Name: Create-Change-Set
              RunOrder: 2
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                ChangeSetName: pipeline-changeset
                RoleArn: !GetAtt CFNRole2CreateResources.Arn
                StackName: !Ref InfrastructureDeploymentStackName
                TemplatePath: !Join [ "::", [ SourceArtifact, !Ref SourceArtifactCode ] ]
              InputArtifacts:
                - Name: SourceArtifact
            - Name: Execute-Change-Set
              RunOrder: 3
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: pipeline-changeset
                StackName: !Ref InfrastructureDeploymentStackName
              InputArtifacts:
                - Name: SourceArtifact