name: Push Image to ECR
run-name: ${{ github.actor }} started workflow
on:
  push:
    branches:
      - 'master'
jobs:
  Explore-GitHub-Actions:
    name: Github Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses : actions/checkout@v3
        with:
          repository: '${{ github.actor }}/${{ github.event.repository.name }}'

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:          
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: MyStack
          template: pipeline-cfn.yaml