name: Push Image to ECR
run-name: ${{ github.actor }} started workflow
on:
  push:
    branches:
      - 'master'

#EDIT ONLY THE ENV VARS. LEAVE THE REST AS IT IS
env:
  S3_Bucket_Name: aws-infra-as-code-cfn-store
  Infrastructure_Stack_Zip_File: infrastructure-cfn.zip
  Infrastructure_Stack_Yaml_File: infrastructure-cfn.yaml
  Infrastructure_Stack_Name: infrastructure-stack

jobs:
  Explore-GitHub-Actions:
    name: Github Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses : actions/checkout@v3
        with:
          repository: '${{ github.actor }}/${{ github.event.repository.name }}'

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:          
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: cicd-pipeline-stack
          template: pipeline-cfn.yaml
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            ArtifactStoreBucket=${{ env.S3_Bucket_Name }},
            SourceArtifactBucket=${{ env.S3_Bucket_Name }},
            SourceArtifact=${{ env.Infrastructure_Stack_Zip_File }},
            SourceArtifactCode=${{ env.Infrastructure_Stack_Yaml_File }},
            InfrastructureDeploymentStackName=${{ env.Infrastructure_Stack_Name }}

      - name: Push 
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
          unzip awscliv2.zip
          sudo ./aws/install
          aws s3api put-object --bucket $S3_Bucket_Name --key dir-1/my_images.tar.bz2